import React, { createContext, useContext } from 'react';
import { useLocalStorage } from '../hooks/useLocalStorage';

type Language = 'es' | 'en' | 'fr';

const translations = {
  es: {
    dashboard: 'Panel de Control',
    listings: 'Listados',
    users: 'Usuarios',
    settings: 'Configuración',
    logout: 'Cerrar Sesión',
    changeAccount: 'Cambiar de cuenta',
    changeAccountDesc: 'Inicia sesión con otro usuario',
    logoutDesc: 'Desconecta tu cuenta actual',
    accountSettings: 'Configuración de la Cuenta',
    accountSettingsDesc: 'Administra tu sesión y preferencias.',
    appPreferences: 'Preferencias de Aplicación',
    language: 'Idioma',
    overview: 'Resumen',
    noData: 'No hay datos disponibles.',
    searchUsers: 'Buscar usuarios...',
    role: 'Rol',
    email: 'Correo',
    actions: 'Acciones',
    login: 'Iniciar Sesión',
    loginWithGoogle: 'Entrar con Google',
    loginToManage: 'Inicia sesión para gestionar',
    admin: 'Administrador',
    supervisor: 'Supervisor',
    owner: 'Propietario',
    user: 'Usuario',
    sessionOptions: 'Opciones de Sesión',
    recentActivity: 'Actividad Reciente',
    totalUsers: 'Usuarios Totales',
    activeListings: 'Listados Activos',
    today: 'Hoy',
    tomorrow: 'Mañana',
    noListForToday: 'No hay una lista de reservas registrada para el día de hoy',
    noListForTomorrow: 'No hay una lista de reservas registrada para mañana',
    totals: 'Totales',
    reviewed: 'Revisadas',
    notReviewed: 'No Revisadas',
    occupied: 'Ocupadas',
    free: 'Libres',
    breakdownByProperty: 'Desglose por Propiedad',
    noneReviewed: 'Ninguna unidad revisada',
    allReviewed: 'Todas las unidades revisadas',
    total: 'Total',
    rev: 'Rev',
    noRev: 'No Rev',
    ocup: 'Ocup',
    newList: 'Nueva Lista',
    archivedLists: 'No hay listas archivadas.',
    userManagement: 'Gestión de Usuarios',
    userManagementDesc: 'Asigna roles y privilegios a los miembros del equipo.',
    currentUserRole: 'Rol Actual',
    ownerImmutable: 'Propietario (Inmutable)',
    loadingUsers: 'Cargando usuarios...',
    noUsersFound: 'No se encontraron usuarios.',
    unknown: 'Desconocido',
    activeReservations: 'Reservas Activas',
    reviewedSection: 'Sección: Revisadas',
    noAdminPermission: 'No tienes permisos de Administrador para ver o editar listas.',
    activeList: 'Lista activa',
    createNewList: 'Crear nueva lista de revisión',
    importReservations: 'Importar Reservas',
    importReservationsDesc: 'Añade o actualiza la lista de check-in / check-out',
    phase1CheckIn: 'Fase 1: Check In',
    crossUnits: 'Cruce de Unidades',
    phase2CheckOut: 'Fase 2: Check Out',
    pasteDataHere: 'Pega aquí los datos de la tabla (TSV/CSV)...',
    pasteDataHereOut: 'Pega aquí los datos de la tabla de salida (TSV/CSV)...',
    clickOrDragImage: 'Haz clic o arrastra una imagen aquí',
    generateBaseList: 'Generar Listado Base',
    crossData: 'Cruzar Datos (Ocupación)',
  },
  en: {
    dashboard: 'Dashboard',
    listings: 'Listings',
    users: 'Users',
    settings: 'Settings',
    logout: 'Logout',
    changeAccount: 'Change Account',
    changeAccountDesc: 'Login with another user',
    logoutDesc: 'Disconnect your current account',
    accountSettings: 'Account Settings',
    accountSettingsDesc: 'Manage your session and preferences.',
    appPreferences: 'App Preferences',
    language: 'Language',
    overview: 'Overview',
    noData: 'No data available.',
    searchUsers: 'Search users...',
    role: 'Role',
    email: 'Email',
    actions: 'Actions',
    login: 'Login',
    loginWithGoogle: 'Sign in with Google',
    loginToManage: 'Sign in to manage',
    admin: 'Admin',
    supervisor: 'Supervisor',
    owner: 'Owner',
    user: 'User',
    sessionOptions: 'Session Options',
    recentActivity: 'Recent Activity',
    totalUsers: 'Total Users',
    activeListings: 'Active Listings',
    today: 'Today',
    tomorrow: 'Tomorrow',
    noListForToday: 'No reservation list registered for today',
    noListForTomorrow: 'No reservation list registered for tomorrow',
    totals: 'Totals',
    reviewed: 'Reviewed',
    notReviewed: 'Not Reviewed',
    occupied: 'Occupied',
    free: 'Free',
    breakdownByProperty: 'Breakdown by Property',
    noneReviewed: 'No units reviewed',
    allReviewed: 'All units reviewed',
    total: 'Total',
    rev: 'Rev',
    noRev: 'No Rev',
    ocup: 'Occup',
    newList: 'New List',
    archivedLists: 'No archived lists.',
    userManagement: 'User Management',
    userManagementDesc: 'Assign roles and privileges to team members.',
    currentUserRole: 'Current Role',
    ownerImmutable: 'Owner (Immutable)',
    loadingUsers: 'Loading users...',
    noUsersFound: 'No users found.',
    unknown: 'Unknown',
    activeReservations: 'Active Reservations',
    reviewedSection: 'Section: Reviewed',
    noAdminPermission: 'You do not have Administrator permissions to view or edit lists.',
    activeList: 'Active list',
    createNewList: 'Create new review list',
    importReservations: 'Import Reservations',
    importReservationsDesc: 'Add or update the check-in / check-out list',
    phase1CheckIn: 'Phase 1: Check In',
    crossUnits: 'Cross Units',
    phase2CheckOut: 'Phase 2: Check Out',
    pasteDataHere: 'Paste table data here (TSV/CSV)...',
    pasteDataHereOut: 'Paste departure table data here (TSV/CSV)...',
    clickOrDragImage: 'Click or drag an image here',
    generateBaseList: 'Generate Base List',
    crossData: 'Cross Data (Occupation)',
  },
  fr: {
    dashboard: 'Tableau de bord',
    listings: 'Annonces',
    users: 'Utilisateurs',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    changeAccount: 'Changer de compte',
    changeAccountDesc: 'Connectez-vous avec un autre utilisateur',
    logoutDesc: 'Déconnectez votre compte actuel',
    accountSettings: 'Paramètres du compte',
    accountSettingsDesc: 'Gérez votre session et vos préférences.',
    appPreferences: 'Préférences de l\'application',
    language: 'Langue',
    overview: 'Aperçu',
    noData: 'Aucune donnée disponible.',
    searchUsers: 'Rechercher des utilisateurs...',
    role: 'Rôle',
    email: 'E-mail',
    actions: 'Actions',
    login: 'Connexion',
    loginWithGoogle: 'Se connecter avec Google',
    loginToManage: 'Connectez-vous pour gérer',
    admin: 'Administrateur',
    supervisor: 'Superviseur',
    owner: 'Propriétaire',
    user: 'Utilisateur',
    sessionOptions: 'Options de session',
    recentActivity: 'Activité récente',
    totalUsers: 'Total des utilisateurs',
    activeListings: 'Annonces actives',
    today: 'Aujourd\'hui',
    tomorrow: 'Demain',
    noListForToday: 'Aucune liste de réservation enregistrée pour aujourd\'hui',
    noListForTomorrow: 'Aucune liste de réservation enregistrée pour demain',
    totals: 'Totaux',
    reviewed: 'Révisé',
    notReviewed: 'Non révisé',
    occupied: 'Occupé',
    free: 'Libre',
    breakdownByProperty: 'Répartition par propriété',
    noneReviewed: 'Aucune unité révisée',
    allReviewed: 'Toutes les unités révisées',
    total: 'Total',
    rev: 'Rév',
    noRev: 'Non Rév',
    ocup: 'Occup',
    newList: 'Nouvelle Liste',
    archivedLists: 'Aucune liste archivée.',
    userManagement: 'Gestion des utilisateurs',
    userManagementDesc: 'Attribuer des rôles et des privilèges aux membres de l\'équipe.',
    currentUserRole: 'Rôle Actuel',
    ownerImmutable: 'Propriétaire (Immuable)',
    loadingUsers: 'Chargement des utilisateurs...',
    noUsersFound: 'Aucun utilisateur trouvé.',
    unknown: 'Inconnu',
    activeReservations: 'Réservations Actives',
    reviewedSection: 'Section : Révisées',
    noAdminPermission: 'Vous n\'avez pas les autorisations d\'administrateur pour afficher ou modifier des listes.',
    activeList: 'Liste active',
    createNewList: 'Créer une nouvelle liste de révision',
    importReservations: 'Importer des réservations',
    importReservationsDesc: 'Ajouter ou mettre à jour la liste des arrivées / départs',
    phase1CheckIn: 'Phase 1 : Arrivée',
    crossUnits: 'Croiser les unités',
    phase2CheckOut: 'Phase 2 : Départ',
    pasteDataHere: 'Collez les données du tableau ici (TSV/CSV)...',
    pasteDataHereOut: 'Collez les données du tableau de départ ici (TSV/CSV)...',
    clickOrDragImage: 'Cliquez ou glissez une image ici',
    generateBaseList: 'Générer la liste de base',
    crossData: 'Croiser les données (Occupation)',
  }
};

type TranslationsContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations.es) => string;
};

const LanguageContext = createContext<TranslationsContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useLocalStorage<Language>('app-language', 'es');

  const t = (key: keyof typeof translations.es) => {
    return translations[language][key] || translations.es[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
